[window]
size = [800,600]
position = [0,0]
vsync = false
title = "tungsten test project"

[general]
quit_on_esc = true

[render]
prefered = "opengl"

[render.vulkan.log]
debug = false
information = false
error = true
warning = true
