[package]
name = "tungsten"
version = "0.0.1"
authors = ["DelSkayn <mees.delzenne@gmail.com>"]

[dependencies]
glutin = "*"
log = "*" 
time = "*"
num_cpus = "*"
crossbeam = "*"
gfx = "0.9.1"
gfx_window_glutin = "0.9.1"
gfx_device_gl = "0.8.1"
gfx_core= "0.1.1"

[profile.dev]
opt-level = 0
debug = true
rpath = false
lto = false
debug-assertions = true
