[package]
name = "tungsten"
version = "0.0.1"
authors = ["DelSkayn <mees.delzenne@gmail.com>"]

[dependencies]
glutin = "*"
log = "*" 
time = "*"
num_cpus = "*"
crossbeam = "*"
gfx = "*"
gfx_window_glutin = "*"
gfx_device_gl = "*"
gfx_core= "*"
lazy_static = "*"
serde = "*"
serde_json = "*"

[profile.dev]
opt-level = 0
debug = true
rpath = false
lto = false
debug-assertions = true

