[package]
name = "tungsten"
version = "0.0.1"
authors = ["DelSkayn <mees.delzenne@gmail.com>"]

[dependencies]
glutin = "*"
log = "*" 
time = "*"
num_cpus = "*"
crossbeam = "*"
lazy_static = "*"
serde = "*"
serde_json = "*"
serde_macros = "*"
task = { git = "https://gitlab.com/DelSkayn/task-rs.git" }
toml = "*"

[profile.dev]
opt-level = 0
debug = true
rpath = false
lto = false
debug-assertions = true

